apiVersion: v1
kind: Service
metadata:
  name: auctionsniper
  namespace: default
  labels:
    app: auctionsniper
spec:
  selector:
    app: auctionsniper
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
